# pages/home.py
import streamlit as st
import pandas as pd
from PIL import Image
import os

def render():

    st.markdown("""
    ## The Growing Importance of Deepfake Detection

    Since their emergence in 2017, deepfakes have advanced significantly in both technical capability and real-world influence.
    Today, synthetic images generated by GANs and diffusion models can appear highly realistic, making reliable detection methods increasingly important.
    """)

    # ==========================
    # COLUMN STATISTICS
    # ==========================

    c1, c2, c3, c4, c5= st.columns([1, 1, 1, 1, 1])

    with c2:
            st.markdown("""
            <div style="
                background: #ffffff;
                padding: 24px;
                border-radius: 12px;
                box-shadow: 0 4px 12px rgba(0,0,0,0.08);
                text-align: center;
                border: 1px solid #e6e6e6;
                margin-top: 20px;
                margin-bottom: 20px;
            ">
                <h3 style="margin-bottom: 6px; color:#333;">Dec 2018</h3>
                <p style="
                    font-size: 40px; 
                    font-weight: 800; 
                    color:#2E86C1;
                    margin: 0;
                ">
                    7,964
                </p>
                <p style="
                    font-size: 15px;
                    color: #666;
                    margin-top: 4px;
                ">
                    Reported by Deeptrace (2019)
                </p>
            </div>
            """, unsafe_allow_html=True)

        
    with c4:
            st.markdown("""
            <div style="
                background: #ffffff;
                padding: 24px;
                border-radius: 12px;
                box-shadow: 0 4px 12px rgba(0,0,0,0.08);
                text-align: center;
                border: 1px solid #e6e6e6;
                margin-top: 20px;
                margin-bottom: 20px;
            ">
                <h3 style="margin-bottom: 6px; color:#333;">Jun 2019</h3>
                <p style="
                    font-size: 40px; 
                    font-weight: 800; 
                    color:#2E86C1;
                    margin: 0;
                ">
                    14,678
                </p>
                <p style="
                    font-size: 15px;
                    color: #666;
                    margin-top: 4px;
                ">
                    Reported by Deeptrace (2019)
                </p>
            </div>
            """, unsafe_allow_html=True)
     
     
    st.markdown("""
        Deeptrace reported in 2019 that the number of detected deepfake videos almost doubled within seven months, rising from 7,964 in December 2018 to 14,678 by mid 2019.
        The scale of global internet usage also significantly increases the risks posed by synthetic media. Cisco reports that by 2023 nearly two thirds of the world’s population, 
        or 5.3 billion people, will be online, creating an immense audience for digital content. 
    """)
    
    root = os.path.dirname(os.path.dirname(__file__))  

    img_path = os.path.join(root, "imgs", "bar_char.png")
    img = Image.open(img_path)

    col1, col2, col3 = st.columns([1, 2, 1])  

    with col2:
        st.image(img, use_column_width=True, caption="Internet Statistics")
    
    st.markdown("""
        The number of connected devices is projected to surpass 29 billion, with each person owning more than three on average. 
        In such a highly connected ecosystem, manipulated media can spread rapidly across consumer and machine-to-machine networks, amplifying the global impact of deepfake content. 
    """)

    # ==========================
    # MOTIVATION
    # ==========================

    st.markdown("""
    ## Motivation

    This project aims to investigate and compare the effectiveness of Machine Learning (ML) and Deep Learning (DL) models in detecting deepfake images.  
    The evaluation focuses on accuracy, efficiency, and generalization across standardized datasets.
    """)

    # ==========================
    # OBJECTIVES
    # ==========================

    st.markdown("""
    ## Project Objectives

    - Analyse the dataset to understand image characteristics before model development.  
    - Extract forensic features such as **PRNU**, **LBP**, **DCT**, and **FFT** for ML-based detection.  
    - Build and train ML models using handcrafted features.  
    - Design and train a **CNN model** that learns directly from raw images.  
    - Compare ML and DL model performance.  
    - Develop an interactive application for real-time deepfake detection.
    """)

    st.markdown("<br>", unsafe_allow_html=True)

    # ==========================
    # DEVELOPMENT TOOLS TABLE
    # ==========================

    st.markdown("## Development Tools & Technologies")

    tools_data = {
        "Technology": [
            "Python 3",
            "Numpy & Pandas",
            "OpenCV",
            "scikit-learn",
            "TensorFlow / Keras",
            "Matplotlib & Seaborn",
            "Streamlit"
        ],
        "Purpose": [
            "Core programming language",
            "Data manipulation and numerical processing",
            "Image preprocessing and transformations",
            "Machine learning models and evaluation",
            "Deep learning and CNN training",
            "Data visualization and analysis",
            "Interactive user interface for deployment"
        ]
    }

    df_tools = pd.DataFrame(tools_data)
    st.table(df_tools)
